### ISSUE TITLE
How to get in contact with you

### ISSUE THREAD

**Issue by Davide-sd** [Peter230655/skills-introduction-to-github#1]
Hello @Peter230655 ,

My name id Davide, a fellow SymPy user interested in dynamics. I'd like to get in contact with you. I've checked your GitHub profile but I couldn't find any way to get in contact with you, except opening this issue. 

I noticed your interests in symbolic dynamics and I'd like to ask you a few questions about Kane's method and SymPy. But I'd like the conversation to remain private. If you look at my GitHub profile, you should find my email address. Can't wait to chat with you :)

Feel free to close this issue.

**Comment by Peter230655** [comment]
I sent an email to you.
